node_id: "node-5"
bind_address: "0.0.0.0"
advertise_addr: "node5"
node_port: 7005
seed_peers:
  - "node2:7002"
  - "node4:7004"
gossip_interval_ms: 1000
fanout: 2
membership_timeout_ms: 10000
aggregation_type: "topk"
initial_value: 40.0
top_k_size: 3
log_level: "info"
