node_id: "node-6"
bind_address: "0.0.0.0"
advertise_addr: "node6"
node_port: 7006
seed_peers:
  - "node3:7003"
  - "node5:7005"
gossip_interval_ms: 1000
fanout: 2
membership_timeout_ms: 10000
aggregation_type: "topk"
initial_value: 60.0
top_k_size: 3
log_level: "info"
